project3

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,3 +1,4 @@
+   
 version: 2.1
 
 commands:
@@ -17,15 +18,13 @@ commands:
           when: on_fail
           command: |
             aws s3 rm s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
-
-
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.     
     steps:
       - run:
           name: Revert migrations
           command: |
-            cd ./project/backend
+            cd ~/project/backend
             npm install
             npm run migrations:revert
           when: on_fail
@@ -66,34 +65,39 @@ jobs:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - restore_cache:
-          keys: [frontend-build]
+      - attach_workspace:
+          at: .
       - run:
-          name: Build front-end
+          name: Frontend Build
           command: |
             cd frontend
-            npm install
+            npm i
             npm run build
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: frontend-build
+      - persist_to_workspace:
+          root: .
+          paths:
+            - frontend/dist
 
   build-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - restore_cache:
-          keys: [backend-build]
+      - attach_workspace:
+          at: .
       - run:
-          name: Back-end build
+          name: Backend build
           command: |
             cd backend
-            npm install
+            npm i
             npm run build
-      - save_cache:
-          paths: [backend/node_modules]
-          key: backend-build
+            pwd
+            ls -la
+            
+      - persist_to_workspace:
+          root: .
+          paths:
+            - backend/dist
 
 
   test-frontend:
@@ -101,92 +105,103 @@ jobs:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - restore_cache:
-          keys: [frontend-build]
       - run:
-          name: test-frontend
+          name: test frontend
           command: |
             cd frontend
-            npm install
-            npm run test
+            npm i
+            npm test
                 
   test-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - restore_cache:
-          keys: [backend-build]
       - run:
-          name: backend-build
+          name: test backend
           command: |
             cd backend
-            npm install
-            npm run test
-
+            npm i
+            npm test
   scan-frontend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - restore_cache:
-          keys: [frontend-build]
       - run:
-          name: frontend-build
+          name: Check Frontend against security vulnerabilities
           command: |
             cd frontend
-            npm install
+            npm i
             npm audit fix --audit-level=critical --force
+      - restore_cache:
+          key: v1-frontend-build
 
   scan-backend:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
-      - restore_cache:
-          keys: [backend-build]
       - run:
-          name: backend-build
+          name: Check Backend against security vulnerabilities
           command: |
-            cd backend
-            npm install
+            cd backend; ls -la
+            npm i
             npm audit fix --audit-level=critical --force
+      - restore_cache:
+          key: v1-backend-build 
 
   deploy-infrastructure:
     docker:
       - image: amazon/aws-cli
     steps:
+      
       - checkout
       - run:
-          command: yum install -y tar gzip
+          name: Install dependencies
+          command: yum install -y tar gzip      
       - run:
           name: Ensure back-end infrastructure exists
+          working_directory: ./.circleci/files
           command: |
-              aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
+            aws cloudformation deploy \
+              --template-file backend.yml --region=us-east-1 \
               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
-              --tags project=udapeople
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --tags project=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}              
       - run:
           name: Ensure front-end infrastructure exist
+          working_directory: ./.circleci/files
           command: |
-              aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
+            aws cloudformation deploy \
+              --template-file frontend.yml --region=us-east-1 \
               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
-              --tags project=udapeople
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --tags project=udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}              
+#      - run:
+#          name: Save backend URL in memstash
+#          command: |
+#            BACKEND_IP=$(aws ec2 describe-instances \
+#              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#              --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+#              --output text)
+#            echo "$BACKEND_IP"
+#            curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "http://$BACKEND_IP:3030" https://api.memstash.io/values/BACKEND_URL
+            
+
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query "Reservations[*].Instances[*].{public_ip:PublicIpAddress}" --output text)
-            echo $BACKEND_IP >> .circleci/ansible/inventory.txt
-            echo $BACKEND_IP > .circleci/ansible/backend_host.txt
-      
+            echo -e "[web]\n" > inventory.txt
+            aws ec2 describe-instances \
+              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --output text >> inventory.txt 
+              cat inventory.txt
       - persist_to_workspace:
-          root: ~/
+          root: .
           paths:
-            - project/.circleci/ansible/inventory.txt
-            - project/.circleci/ansible/backend_host.txt
+            - .circleci/ansible/inventory.txt
           
 
       - destroy-environment
@@ -197,23 +212,27 @@ jobs:
       - image: python:3.7-alpine3.12
     steps:
       - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            yum install -y epel-release
-            yum install -y tar gzip ansible
-      - attach_workspace:
-          name: Attach Workspace
-          at: ~/      
       - add_ssh_keys:
           fingerprints: ["2e:5d:96:41:cb:53:cf:04:22:c6:5b:9c:a9:5b:4c:ef"]
+      - attach_workspace:
+          at: .
+      - run:
+          name: Install dependencies
+          working_directory: ./.circleci/ansible
+          command: |
+            apk add --update ansible
+            ansible --version
+            pip3 install --upgrade pip
+            pip3 install awscli
+            aws --version
       - run:
           name: Configure server
+          working_directory: ./.circleci/ansible
           command: |
-            cd .circleci/ansible
+            pwd &&
+            cat inventory.txt
             ansible-playbook -i inventory.txt configure-server.yml
       - destroy-environment
-
 
   run-migrations:
     docker:
@@ -223,34 +242,19 @@ jobs:
       - attach_workspace:
           at: .
       - run:
-          name: Install AWS CLI dependencies
-          working_directory: /tmp
-          command: |
-            sudo apt-get update && sudo apt-get install -yy less
-            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-            unzip awscliv2.zip
-            sudo ./aws/install
-      - run:
           name: Run migrations
-          no_output_timeout: 30m
           working_directory: ./backend
           command: |
+            ls .
             npm install
-            npm run migrations > migration.log
-            export migration_status=$(cat migration.log | grep -c "has been executed successfully")
-            tar -zcvf ~/backend.tar.gz .
-            ls
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - migration.log
-            - backend.tar.gz
+            npm run migrations > migration_dump.txt
+            cat migration_dump.txt
       - run:
           name: Send migration results to memstash
-          command: |
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
+          command: |        
+            if grep -q "has been executed successfully" migration_dump.txt
             then
-              curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
+            curl -H "Content-Type: text/plain" -H "token: 7933fe63-4687-4fa1-8426-aa25aa1730ec" --request PUT --data "success" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID:0:7}
             fi
       - destroy-environment    
                    # Here's where you will add some code to rollback on failure      
@@ -261,35 +265,42 @@ jobs:
     steps:
       - checkout
       - attach_workspace:
-          at: .    
+          at: .      
       - run:
           name: Install dependencies
-          command: |
-            yum install -y epel-release
-            yum install -y tar gzip ansible nodejs npm python3 
-      - run:
-          name: Install AWS CLI
-          command: |
-            yum install awscli -y
-      - attach_workspace:
-          name: Attach Workspace
-          at: ~/                        
+          working_directory: /tmp
+          command: |         
+            sudo apt-get update && sudo apt-get install -yy less
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
       - run:
           name: Get backend url
           command: |
-            export BACKEND_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --query "Reservations[*].Instances[*].{public_ip:PublicIpAddress}" --output text)
+            export BACKEND_IP=`cat .circleci/ansible/inventory.txt | head -2 | tail -1`
             export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
-            cat frontend/.env
+            echo "API_URL = ${API_URL}"
+            echo API_URL="http://${BACKEND_IP}:3030" >> "frontend/.env"
+            echo ENVIRONMENT=production  >> "frontend/.env" 
+            echo NODE_ENV=production >> "frontend/.env"
+      - run:  
+          name: configure server
+          working_directory: ./frontend         
+          command: |
+            npm install
+            cat .env
+            ls -la
+            npm run build
       - run:
           name: Deploy frontend objects
+          working_directory: ./frontend          
           command: |
-            cd frontend
-            npm install
-            npm run build
             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-            aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --recursive
+            aws s3 cp ./dist "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}" --recursive
+      - persist_to_workspace:
+          root: .
+          paths:
+            - frontend/dist
 
       - destroy-environment
       - revert-migrations
@@ -299,41 +310,52 @@ jobs:
       - image: python:3.9.0-alpine
     steps:
       - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            yum install -y epel-release
-            yum install -y tar gzip ansible nodejs npm python3      
       - add_ssh_keys:
           fingerprints: ["2e:5d:96:41:cb:53:cf:04:22:c6:5b:9c:a9:5b:4c:ef"]
       - attach_workspace:
-          name: Attach Workspace
-          at: ~/
+          at: .
+
       - run:
-          name: Deploy backend
+          name: Install dependencies
+          working_directory: ./.circleci/ansible          
           command: |
-            echo ENVIRONMENT=production >> "backend/.env"
-            echo NODE_ENV=production >> "backend/.env"
-            echo TYPEORM_CONNECTION=postgres >> "backend/.env"
-            echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
-            echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
-            echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> "backend/.env"
-            echo TYPEORM_HOST=$TYPEORM_HOST >> "backend/.env"
-            echo TYPEORM_PORT=$TYPEORM_PORT >> "backend/.env"
-            echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
-            echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
-            echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
-            tar -C backend -czvf artifact.tar.gz .
-            cd backend
+            apk add --update ansible curl rsync openssh nodejs npm unzip
+            npm install
+            ansible --version
+            pip3 install --upgrade pip
+            pip3 install awscli
+            aws --version 
+            export ANSIBLE_HOST_KEY_CHECKING=False
+      - run:
+          name: install node modules
+          command: |
+            cd /root/project/backend
+            npm install
+      - run:
+          name: build backend dist
+          command: |
+            cd /root/project/backend
             npm i
             npm run build
-            cd ..
-            tar -C backend -czvf artifact.tar.gz .
-            export ANSIBLE_HOST_KEY_CHECKING=False
-            cd ~/project/.circleci/ansible
-            echo "Contents  of the inventory.txt file is -------"
+            npm run prestart:prod      
+      - run:
+          name: Compress dist files on SYSTEN
+          command: |
+            cd /root/project
+            pwd
+            tar -cvzf backend.tar.gz backend      
+      
+      - run:
+          name: Deploy backend
+          working_directory: ./.circleci/ansible
+          no_output_timeout: 30m          
+          command: |
+            pwd
+            export ANSIBLE_HOST_KEY_CHECKING=False 
+            export host_key_checking=False
+            export record_host_keys=False
             cat inventory.txt
-            ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.txt deploy-backend.yml
+            ansible-playbook -i inventory.txt deploy-backend.yml -vv
       # Here's where you will add some code to rollback on failure
       - destroy-environment
       - revert-migrations 
@@ -347,25 +369,37 @@ jobs:
       - run:
           name: Install dependencies
           command: |
-            yum install -y epel-release
-            yum install -y tar gzip nodejs npm curl awscli
-      - attach_workspace:
-          name: Attach Workspace
-          at: ~/           
+            apk add --update curl
+            pip install awscli
       - run:
           name: Backend smoke test.
           command: |
-            BACKEND_IP=`cat .circleci/ansible/inventory.txt | head -2 | tail -1`
-            echo ${BACKEND_IP}
-            export URL="http://$BACKEND_IP:3030/api/status"
-            echo $URL
-            curl $URL
+            export BACKEND_IP=$(curl -H "Content-Type: text/plain" -H "token: 440bb73b-b904-44f1-ab72-71ade8f9b9e1" --request GET https://api.memstash.io/values/UdaPeople-${CIRCLE_WORKFLOW_ID:0:7}-BackendIP)
+            echo "------------------------------------"
+            echo BACKEND_URL: http://54.172.129.159:3030/api/status
+            echo "------------------------------------"
+            if curl -s http://54.172.129.159:3030/api/status | grep "ok"
+            then
+              echo "Backend Smoke Test Success"
+              exit 0
+            else
+              echo "Backend Smoke Test Failed"
+              exit 1
+            fi
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-eu-west-1.amazonaws.com/#/employees"            
-            echo ${URL} 
-            curl -s ${URL} | grep "Welcome"
+            echo "------------------------------------"
+            echo http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/
+            echo "------------------------------------"
+            if curl -s http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/ | grep "Welcome"
+            then
+              echo "Frontend Smoke Test Success"
+              return 0
+            else
+              echo "Frontend Smoke Test Failed"
+              return 1
+            fi
       - destroy-environment
       - revert-migrations
 
@@ -379,29 +413,24 @@ jobs:
       - run:
           name: Install dependencies
           command: |
-            yum install -y tar gzip
-
+            yum install -y tar gzip curl
+            curl -sL https://rpm.nodesource.com/setup_10.x | bash -
+            yum install -y nodejs
+      - run:
+          name: get old workflow if from memstash for cleanup phase
+          working_directory: ./.circleci/files
+          command: |
+            WorkflowID=$(aws cloudformation \
+              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+              --no-paginate --output text)
       - run:
           name: Update cloudfront distribution
+          working_directory: ./.circleci/files
           command: |
-            export OldWorkflowID=$(aws cloudformation \
-            list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-            --no-paginate --output text)
-            echo $OldWorkflowID > ~/OldWorkflowID.txt
-            cat ~/OldWorkflowID.txt
-                        
-            aws cloudformation deploy \
-            --template-file .circleci/files/cloudfront.yml \
-            --stack-name InitialStack \
-            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-            --tags project=udapeople
-            
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - OldWorkflowID.txt
-
-
+            aws cloudformation update-stack \
+              --use-previous-template \
+              --stack-name InitialStack \
+              --parameters ParameterKey=WorkflowID,ParameterValue=${CIRCLE_WORKFLOW_ID:0:7},UsePreviousValue=false
       - destroy-environment
       - revert-migrations   
 
@@ -469,6 +498,6 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
-#      - cleanup:
-#          requires: [cloudfront-update]
+      - cleanup:
+          requires: [cloudfront-update]
         
